# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_sparsematrixprocessing_wrappers", use_symbols = TRUE, package_name = "sparsematrixprocessing")

#' @usage NULL
#' @useDynLib sparsematrixprocessing, .registration = TRUE
NULL

sparse_degree <- function(matrix) .Call(wrap__sparse_degree, matrix)


# nolint end
