# Generated by extendr: Do not edit by hand

# nolint start

#
# This file was created with the following call:
#   .Call("wrap__make_matrixrowsum_wrappers", use_symbols = TRUE, package_name = "matrixrowsum")

#' @usage NULL
#' @useDynLib matrixrowsum, .registration = TRUE
NULL

#' Compute row sums of a matrix using faer
#'
#' @param x A numeric matrix
#' @return A numeric vector of row sums
#' @export
row_sums_rust <- function(x) .Call(wrap__row_sums_rust, x)


# nolint end
